### ISSUE TITLE
Create a GUI with clicable area

### ISSUE THREAD

**Issue by HydrolienF** [FormikoLudo/FormikoLudoStore#2]
- [x] It should have at least the name of the game
- [ ] a description of the game in the user language
- [ ] It will be nice to have the icon from the repository
- [x] All data are load from a .yml file at `~./launcherjar/availableGames.yml` that look like this:
```yml
HydrolienF:
  Kokcinelo:
    description:
      en: "descEn"
      fr: "descFr"
  Formiko:
    description:
      en: "descEn formiko"
      fr: "descFr formiko"
Sevi2000:
  Sbake:
    description:
      en: "descEn"
```
